"""produto: add campo ativo

Revision ID: a70975cafd2b
Revises: 7cd409af3585
Create Date: 2025-10-06 19:15:52.618599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a70975cafd2b'
down_revision = '7cd409af3585'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ativo', sa.Boolean(), server_default=sa.text('true'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.drop_column('ativo')

    # ### end Alembic commands ###
